[project]
name = "nihil"
version = "0.1.0"
description = "Nihil - Une alternative minimaliste Ã  Exegol"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
nihil = "nihil.controller:main"
