[project]
name = "nihil"
version = "0.1.0"
description = "Nihil - by 0xbbuddha and Goultarde"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
nihil = "nihil.controller:main"
